export const MetricsMatrix = {
  phases: {
    1: {
      name: "1. Concept Phase",
      duration: "1-2 Weeks",
      asset: "Product_Opportunity_Brief.txt",
      raci: {
        product: "A",
        slt: "C",
        sponsor: "None",
        ux: "None",
        dev: "None",
        legal: "None",
        risk: "None",
      },
      correctBlock: "Vision & Strategy Brief",
      hint: "💡 CLUE: Product Management owns the concept definition (A). Secure strategic advice from the SLT (C). Drag the foundational business overview block.",
      desc: "Define product vision & strategic parameters alignment. Pinpoint market gaps and create high-level user hypothesis vectors.",
      docText:
        "========================================================================\n                 STRATEGIC PRODUCT OPPORTUNITY BRIEF\n========================================================================\n[STAGE 1 LOG] STATUS: APPROVED & ARCHIVED\n\n1. OVERARCHING VISION & POSITIONING\n------------------------------------------------------------------------\nObjective: Articulate the north-star goal of the initiative and map\nhow it directly influences long-term competitive advantages.\n\n2. OPPORTUNITY ANALYSIS & POSITIONING VECTORS\n------------------------------------------------------------------------\nMarket Discovery: Map structural gaps, identify user workflow friction\nindicators, and lock in the core problem statement hypothesis.",
    },
    2: {
      name: "2. Discovery Phase",
      duration: "2-4 Weeks",
      asset: "Business_Requirements_Document.txt",
      raci: {
        product: "A",
        slt: "C",
        ux: "None",
        sponsor: "None",
        dev: "None",
        legal: "None",
        risk: "None",
      },
      correctBlock: "BABOK Market Analysis Mapping",
      hint: "💡 CLUE: Business analysis must comply with BABOK methods. Product remains Accountable (A) and SLT provides constraint advice (C).",
      desc: "Conduct qualitative user research interviews, audit competitive market variants, and scope down requirements under strict BABOK criteria.",
      docText:
        "========================================================================\n                BUSINESS REQUIREMENTS DOCUMENT (BRD)\n========================================================================\n[STAGE 2 LOG] STATUS: BABOK COMPLIANT SIGN-OFF\n\n1. BUSINESS ANALYSIS BODY OF KNOWLEDGE (BABOK) WORKSPACE\n------------------------------------------------------------------------\nScope Boundaries: Review quantitative customer surveys, process \nfunnel drop-offs, and competitive positioning metrics.\n\n2. TARGET DEMOGRAPHICS & SCOPED PROBLEM STATEMENT\n------------------------------------------------------------------------\nRefinement Framework: Narrow broad assumptions into high-fidelity user\njourney profiles and measurable operational bottlenecks.",
    },
    3: {
      name: "3. Stakeholder Engagement",
      duration: "1-2 Weeks",
      asset: "Executive_Business_Case.txt",
      raci: {
        product: "A",
        sponsor: "A",
        slt: "I",
        legal: "C",
        ux: "None",
        dev: "None",
        risk: "None",
      },
      correctBlock: "PMBOK Triple Constraint Baseline",
      desc: "Gather constraints, operational legal risks, and structure budget cost analysis under PMBOK triple-constraint guidelines.",
      hint: "💡 CLUE: PMBOK needs the Project Sponsor and PM to align on approvals (A). Legal must vet risks (C), and SLT gets a passive push update (I).",
      docText:
        "========================================================================\n                  EXECUTIVE BUSINESS CASE FRAMEWORK\n========================================================================\n[STAGE 3 LOG] STATUS: FINANCIAL BASELINE BASALED\n\n1. PMBOK TRIPLE-CONSTRAINT SYSTEM ANALYSIS\n------------------------------------------------------------------------\n• Schedule Baseline: Formulate time-boxed project milestones roadmap.\n• Cost Baseline: Complete deep capital and infrastructure budget matrix.\n• Scope Baseline: Map internal constraints and legal risks.",
    },
    4: {
      name: "4. Stories & Specs",
      duration: "2-3 Weeks",
      asset: "Product_PRD_Spec_Sheet.txt",
      raci: {
        ux: "C",
        dev: "C",
        product: "None",
        slt: "None",
        sponsor: "None",
        legal: "None",
        risk: "None",
      },
      correctBlock: "Epic Breakdown & Lifecycle Flows",
      hint: "💡 CLUE: Design and Engineering need to be collaborated with early before building (C). Leave management out for this specific chunk.",
      desc: "Slice wide feature scope down into manageable epics and customer-centric user stories, following strict agile acceptance criteria metrics.",
      docText:
        "========================================================================\n               PRODUCT REQUIREMENT DOCUMENTATION (PRD)\n========================================================================\n[STAGE 4 LOG] STATUS: USER STORIES REFINED\n\n1. AGILE SPECIFICATION & TRANSITIVE EPIC MAPS\n------------------------------------------------------------------------\nRequirements Matrix: Slice major feature components into functional epics.\nFormat standard: 'As a [user type], I want to [action], so that [benefit].'\n\n2. CORE LIFE TRACK STAGES OVERVIEW\n------------------------------------------------------------------------\nLifecycle Tracking: Discovery -> Definition -> Delivery -> Launch & Iteration.",
    },
    5: {
      name: "5. Tech Engagement",
      duration: "1-2 Weeks",
      asset: "MVP_Scoping_Matrix.txt",
      raci: {
        product: "A",
        dev: "R",
        slt: "None",
        sponsor: "None",
        ux: "None",
        legal: "None",
        risk: "None",
      },
      correctBlock: "Technical Debt & Feasibility Audit",
      hint: "💡 CLUE: Product is Accountable (A) for what to build, but Dev Team is Responsible (R) for the technical execution. Grab the Tech Debt block.",
      desc: "Facilitate a technical refinement session with engineering architects to analyze technical debt constraints and map database metrics onto the Roadmap.",
      docText:
        "========================================================================\n                       MVP SCOPING SPECIFICATION\n========================================================================\n[STAGE 5 LOG] STATUS: FEASIBILITY GRANTED\n\n1. TECHNICAL ROADMAP & FEASIBILITY CONSTRAINTS\n------------------------------------------------------------------------\nArchitecture Review: Map database changes, check safety parameters,\nand catalog legacy code technical debt impact vectors.\n\n2. MINIMUM VIABLE PRODUCT (MVP) BOUNDARIES\n------------------------------------------------------------------------\nScoping Strategy: Trim high-complexity items to fit the sprint loop.",
    },
    6: {
      name: "6. Sprints & Development",
      duration: "2-4 Weeks",
      asset: "Sprint_Backlog_Commitment.txt",
      raci: {
        dev: "R",
        product: "None",
        slt: "None",
        sponsor: "None",
        ux: "None",
        legal: "None",
        risk: "None",
      },
      correctBlock: "Agile Scrum Bible Ceremony Loop",
      hint: "💡 CLUE: Sprints are executed entirely by the Dev Team (R). Look for the Agile Scrum ceremony tracking component.",
      desc: "Commit prioritized technical backlog to time-boxed 1-2 week engineering cycles using story-points and facilitate daily alignment standups.",
      docText:
        "========================================================================\n                  SPRINT BACKLOG COMMITMENT MATRIX\n========================================================================\n[STAGE 6 LOG] STATUS: BACKLOG LOCKED TO ITERATION\n\n1. AGILE SCRUM BIBLE METHODOLOGY TRACKING\n------------------------------------------------------------------------\nSizing Units: Allocate developer Story-Points to active user epics.\nCeremony Flow: Sprint Planning -> Daily Standup -> Iteration Delivery.",
    },
    7: {
      name: "7. Test Phase",
      duration: "1-2 Weeks",
      asset: "QA_UAT_Signoff_Log.txt",
      raci: {
        product: "A",
        dev: "R",
        slt: "None",
        sponsor: "None",
        ux: "None",
        legal: "None",
        risk: "None",
      },
      correctBlock: "User Acceptance Testing (UAT) Controls",
      hint: "💡 CLUE: Product approves the sign-off (A), while Dev runs the functional tests (R). Drag the User Acceptance Testing controller block.",
      desc: "Run deep functional regression testing against acceptance criteria logs and coordinate formal staging User Acceptance Testing (UAT).",
      docText:
        "========================================================================\n                   QUALITY ASSURANCE SIGN-OFF LOG\n========================================================================\n[STAGE 7 LOG] STATUS: STAGING PASS PROTOCOL\n\n1. FUNCTIONAL REGRESSION VALIDATION PIPELINES\n------------------------------------------------------------------------\nUAT Matrix: Execute validation cycles against PRD acceptance criteria.\nSecurity Checklist: Audit data privacy protocols and system latency loops.",
    },
    8: {
      name: "8. Iterate Phase",
      duration: "1 Week",
      asset: "Retrospective_Action_Plan.txt",
      raci: {
        dev: "R",
        product: "None",
        slt: "None",
        sponsor: "None",
        ux: "None",
        legal: "None",
        risk: "None",
      },
      correctBlock: "Sprint Retrospective Workflow Refinement",
      hint: "💡 CLUE: Refining development workflows is driven by the engineering team (R). Grab the Retrospective refinement block.",
      desc: "Catalog observed defects and UX friction loops, execute team retrospectives, and document the Retrospective Action Plan.",
      docText:
        "========================================================================\n                  SPRINT RETROSPECTIVE ACTION PLAN\n========================================================================\n[STAGE 8 LOG] STATUS: RETRO MANIFEST FILED\n\n1. REFINEMENT & DEVELOPMENT TEAM OPTIMIZATION\n------------------------------------------------------------------------\nFeedback Loop: Document defects, capture edge cases, and design fast\ncode revisions to optimize process speed for the next cycle.",
    },
    9: {
      name: "9. Launch Phase",
      duration: "1-2 Weeks",
      asset: "GoToMarket_Release_Deck.txt",
      raci: {
        product: "A",
        sponsor: "I",
        slt: "I",
        dev: "R",
        ux: "None",
        legal: "None",
        risk: "None",
      },
      correctBlock: "Usage & Adoption Telemetry Logging",
      desc: "Coordinate with marketing on release logs, deploy phased rollouts via feature flags, and initialize automated adoption tracking dashboards.",
      hint: "💡 CLUE: PM owns launch accountability (A), devs push the code switches (R), while the Sponsor and SLT get push notification updates (I).",
      docText:
        "========================================================================\n                     GO-TO-MARKET RELEASE PLAYBOOK\n========================================================================\n[STAGE 9 LOG] STATUS: LIVE ROLLOUT IN RUNTIME\n\n1. PHASED ROLLOUT CHANNELS & INFRASTRUCTURE WATCH\n------------------------------------------------------------------------\nStability Vectors: Scale feature flags safely (1% -> 10% -> 100%).\nSupport Readiness: Coordinate user guides, release metrics, and training.",
    },
    10: {
      name: "10. Add Feature Expansion",
      duration: "Ongoing",
      asset: "Iterative_Optimization_Roadmap.txt",
      raci: {
        product: "A",
        cx: "C",
        slt: "None",
        sponsor: "None",
        ux: "None",
        dev: "None",
        legal: "None",
        risk: "None",
      },
      correctBlock: "Sentiment Instrumentation Hooks (NPS/CSAT)",
      desc: "Measure initial launch success against baseline OKRs, monitor feedback channels, and prioritize upcoming features.",
      hint: "💡 CLUE: Product owns the optimization roadmap (A). Consult heavily with CX experts (C) to track sentiment tracking loops.",
      docText:
        "========================================================================\n                   ITERATIVE OPTIMIZATION ROADMAP\n========================================================================\n[STAGE 10 LOG] STATUS: CYCLE COMPLETE • TUNNELED BACK TO NODE 1\n\n1. PRODUCTION SENTIMENT METHODOLOGY INSTRUMENTATION\n------------------------------------------------------------------------\nProduct Health HUD: Track Customer Satisfaction (CSAT), Customer Effort \nScore (CES), and net promoter sentiment tracking loops (NPS).",
    },
  },
};
